[package]
name = "celeste"
version = "0.0.1"
authors = ["leo60228 <iakornfeld@gmail.com>"]
edition = "2018"
description = "Crate for formats from the 2018 game Celeste."
license = "MIT OR Apache-2.0"

[dependencies]
nom = "^4.1"
