[package]
name = "celeste_derive"
version = "0.1.0"
authors = ["leo60228 <iakornfeld@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.26"
quote = "0.6.11"
heck = "0.3.1"

[dev-dependencies.celeste]
path = ".."
version = "1.0.1"
default-features = false
