name: Rust

on: [push]

jobs:
  test:
    name: tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - name: Update Rust
        run: rustup update
      - name: Version
        run: rustup --version && cargo --version --verbose && rustc --version --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          CELESTE_DIALOG_URL: ${{ secrets.CELESTE_DIALOG_URL }} # password protected
        run: cargo test --verbose && cargo test --verbose -- --ignored
  lint:
    name: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Idioms
        run: cargo clippy --all -- -D clippy::all
