name: Rust

on: [push]

jobs:
  test:
    name: tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  lint:
    name: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Idioms
        run: cargo clippy --all -- -D clippy::all
